import { ReactNode } from "react";
import { Html, Head, Main, NextScript } from "next/document";

export default function Document({ children }: { children: ReactNode }) {
  return (
    <Html lang="en">
      <Head />
      <title>GENAIMAGE</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <body>
        {children}
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
